conjure-cp/conjure

src/Conjure/Compute/DomainUnion.hs
Instead of appending two lists of domains together, `DomainUnion` now performs the union of both lists, leaving all ranges unique and living up to its name.
Old behaviour:
```haskell
domainUnion (DomainInt [ r1, r2 ]) (DomainInt [ r2, r3 ])
= DomainInt [ r1, r2, r2, r3 ]
```
New behaviour:
```haskell
domainUnion (DomainInt [ r1, r2 ]) (DomainInt [ r2, r3 ])
= DomainInt [ r1, r2, r3 ]
```
=> DomainUnion performs actual union of domains

docs/conf.py, docs/conjure-help.html, docs/conjure-help.txt, src/Conjure/UI.hs, tests/golden/conjure-help.txt
Branching this as it is quite a big source change.
This cuts the amount of text printed by the CLI help facility, while (hopefully) retaining the meaning.
=> reduce CLI help verbosity

src/Conjure/Language/Domain/AddAttributes.hs
Adding a size attribute to a `set` or `mset` domain will merge the values being added if an existing size attribute of the given type is present, using `max` for `minSize` and `min` for `maxSize`.
It only applies to size attributes on sets and multisets for now, in case a different implementation is preferred or if the change is not desirable. Extending it to other domains will be repetitive but not difficult.
An example of this change being applied follows, and does indeed fire with a `MainHelper.hs` modified for the contrived example. Calling `addAttributesToDomain` with `minSize 5` will now update the internal Essence spec to be `minSize max([3, 5])` and the output Essence' to be `minSize 5`. The previous behaviour was to fail.
```essence
find s : set (minSize 3) of int(1..10)
==> find …
```
=> Same size attributes are merged instead of failing

src/Conjure/UI/ParameterGenerator.hs
Hi Oz,
I'd like to replace the middle/delta in our current rewriting rules to min/max. The changes are done in this pull request (I just followed your examples in the code to make the change). I tested it myself and it seems fine. Could you please help to check if it's okay? 
There are two reasons for this change:
- the forbidden constraints on cardinality (to eliminate trivially unsat generator instances) are much easier to express using min/max
- previously we had middle/delta to avoid the need for correcting values when min>max during the tuning, but now since we will have the repairing mechanism implemented, we can easily expose this as a forbidden constraint to ensure min<=max
- using min/max also makes post-analysis on generator configuration space easier to be interpreted. This …
=> paramgen: change middle/delta to min/max

src/Conjure/UI/MainHelper.hs
At the moment the JSON file isn't valid JSON, as it contains $ comments
With this change the whole file isn't a single JSON object, but a stream of JSON objects -- some languages (including GAP) are happy reading such a stream.
=> Remove comment files from JSON output, so the file is a valid stream of JSON objects

etc/build/install-gecode.sh, src/Conjure/UI/MainHelper.hs, tests/custom/issues/478/stderr.expected, tests/custom/issues/478/stdout.expected
At the moment the 'JSON' pretty printing sometimes prints a message (when it is given a solution, or param). The problem is, this message makes the output invalid JSON.
Therefore, instead print the message to stderr. This will make the output the same for the terminal reader, but mean anyone who cares can redirect stderr to /dev/null
=> Print message to stderr, to make it easier to skip

.github/workflows/docker-publish.yml
Add caching to build-push-action, and remove unnecessary workflow steps. Also adds a ccache setup step, to help speed up build times.
=> Update docker-publish.yml to include some basic caching

docs/conf.py, docs/tutorials/knapsack_generator/KnapGen.rst
Sphinx-doc 5.x now wants underlines in RST files to match the length of the heading.
=> correct underlines for stricter RST syntax checking in recent sphinx-doc

etc/build/install-z3.sh
1. Update z3 to 4.11.2 (was 4.8.8) and refactored to use version only in one place. In future the desired version numbers could perhaps be read from a configuration file?
2. Now tries to use python3 if python is not found. I am not sure this works on all platforms we target as it needs `which` to be in the path (this is `/usr/bin/which` on macOS). Another solution is probably more elegant, this was the first reasonable one I found.
=> update Z3 version, remove implicit dependency on Python 2 for build

etc/build/install-z3.sh
This replaces my previous use of `which` by `command -v` in the Python detection code as per https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script to hopefully make the Z3 build more portable.
=> replace which by command as per POSIX

docs/conf.py, docs/installation.rst
As documented in issue #523 the documentation currently may fail to build on recent systems. The automated build testing system and the system used by `readthedocs.org` seem to be using an older version Sphinx-2.x rather than current Sphinx-5.x so this isn't necessarily obvious to most people, but will likely become a problem if either or both of these systems upgrade to a more recent toolchain.
Here I have documented the minimal pip3 command needed, and mentioned the TeX requirements, also fixing the incompatibility in `conf.py` which prevented `make docs` working: in Sphinx-3.x the `add_lexer` API changed to require a class rather than a function.
I think this should still work on a reasonably recent Sphinx-2.x toolchain as the API apparently allowed both calling conventions during that …
=> upgrade to Sphinx-5.x and document requirements

src/Conjure/Language/Pretty.hs, tests/custom/issues/517/517.essence, tests/custom/issues/517/run.sh
#517 
Disclaimer: This was implemented entirely using GitHub Codespaces (without sufficient RAM to build the whole project) on my mobile phone during toilet breaks with zero experience in Haskell. Please be gentle!
=> Escape more characters in JSON output. Fixes #517

Makefile, etc/build/silent-wrapper.sh
1) autoconf is also listed as a dependecy.
2) use a more specialised naming scheme for the stderr and stdout files so they can be safely deleted.
=> Improve make solvers

docs/notebooks/division_and_mod_demonstration.ipynb
This should fix the division_and_mod  colab link
=> put in division_and_mod_demonstration using colaboratory

.gitignore, docs/bits.rst, docs/bits/attribute/L_regular.md, docs/bits/function/allDiff.md, docs/bits/function/and.md, docs/bits/function/max.md, docs/bits/function/min.md, docs/bits/keyword/expr_projection.md, docs/bits/keyword/find.md, docs/bits/keyword/new_type_enum.md, docs/bits/operator/L_Div.md, docs/bits/operator/L_Mod.md, docs/bits/operator/L_in.md, docs/build.sh, docs/conf.py, docs/contact.rst, docs/index.rst, docs/requirements.txt
Calling `bash build.sh` in the docs directory should build the documentation locally.
pinging @N-J-Martin, @hz66-404, and Georgii, but I don't know his Github username.
I suggest:
- We use a level-1 heading in each file (a single `#`) so they are consistent.
- We use a title that is:
- just the keyword itself if the token is a word (regular, max, allDiff etc)
- the symbol and a  description if the token is a symbol (see / (integer division)).
I think I did this consistently for the existing _bits_, but it'll be good if someone takes a look and double-checks!
=> Adding the "bits" in the documentation to sphinx

Makefile, docs/build.sh, docs/installation.rst
Remove outdated information about supported GHC versions. Also repharase the SR text and remove the doc compilation section
=> Remove outdated information about supported GHC versions

Dockerfile, Makefile, etc/build/install-ortools.sh, tests/allsolvers/run.sh, tests/allsolvers/stdout.expected
Hi, I have noticed that, in some Linux systems, the script to install or-tools wasn't working properly: the compilation was successful but at, execution time, the Or-tools solver would throw an exception because it could not locate a shared library it needed. The library was present but it was located in the binary directory and not in the shared library directory. To fix this issue, I have added an if statement that checks if the shared binary folder is present and if it is, the libraries will be copied there. I have also added a message to inform the user on how to act in case the solver doesn't work.
=> Fixed or-tools install script

.github/workflows/release.yml, .github/workflows/solvers.yml, Dockerfile, Makefile, docs/conjure-help.html, docs/conjure-help.txt, etc/build/install-runsolver.sh, etc/build/runsolver.patch, etc/build/silent-wrapper.sh, src/Conjure/Process/Enumerate.hs, src/Conjure/UI.hs, src/Conjure/UI/MainHelper.hs
The new command line options are the following:
```
runsolver:
--runsolver-cpu-time-limit=INT          Use runsolver to limit total CPU time (in seconds)
--runsolver-memory-limit=INT            Use runsolver to limit total memory usage (Maximum RSS - in megabytes).
```
=> Add runsolver support

essence.gitignore
Add a gitignore template for Essence and Essence Prime modelling, in the style of https://github.com/github/gitignore.
I could not find a good list of intermediate and output files for Conjure and Savile Row; having this in an easy to find place would be helpful.
=> Add gitignore template for Essence and Essence Prime

Dockerfile
The originally used base image: 23.10, is no longer supported. This commit updates it to image version: 24.10 which is the most recent release and is supported until July 2025.
=> build: update ubuntu base image version

etc/build/install-minizinc.sh
This is to have a consistent MiniZinc version across AutoIG and Conjure (AutoIG uses 2.8.5 which was released on 3 June 2024).
=> build: updated minizinc version from 2.8.3 to 2.8.5

etc/build/install-stack.sh
This just adds auto-downloading of stack for ARM macs. Tested on an arm mac, hopefully I didn't break intel ones!
The place where stack is normally downloaded from doesn't have arm -- I don't know if it's sensible to move over to https://get.haskellstack.org/stable/ for other OSes. For information, this downloads:
```Version 3.3.1, Git revision 7540878295db1899b55855cc765ab1eacdf30f3c aarch64 hpack-0.37.0```
=> Add support for downloading stack on arm macs
