conjure-cp/conjure

docs/Makefile
docs/cli.rst
docs/demonstrations.rst
docs/essence.rst

To begin with, some small documentation changes, broken down into separate changes.

Docs smallfixes

---

docs/essence.rst

add partition

---

src/Conjure/UI/Model.hs
tests/custom/basic/comprehension-cardinality/comp.essence
tests/custom/basic/comprehension-cardinality/comp.solution
tests/custom/basic/comprehension-cardinality/run.sh
tests/custom/basic/comprehension-cardinality/stdout.expected

added rewrite for opTwoBars on comprehension

---

tests/exhaustive/mildly_interesting/cyclic_graph/expected/model.eprime

Fix for #475
I think this probably wasn't noticed when the change was made since it is a long running test. But Azure picked it up!

change expected output of test

---

docs/tutorials/knapsack.rst

Fixed a couple of grammar issues, made references to keywords and variable names consistently use code markup (like the live conjure tutorials).  Also fixed a dodgy `given`.

Proofreading, minor changes

---

docs/tutorials/Groups.rst

Consistent code markup and a couple of grammar / spelling corrections.

Proofreading, minor tweaks

---

src/Conjure/UI/MainHelper.hs

Does this fix it you think @ott2?

Add an additional command line argument to SR so it does not have to guess which solver to use (fix #505)

---

Makefile

See issue #557 for more details.

ensure BIN_DIR is in path, needed for Homebrew formula build: fixes #557

---

docs/tutorials/notebooks/KnapsackProblem.ipynb

This is a pull request for the Knapsack Problem notebook tutorial.

Notebook tutorial for Knapsack Problem.

---

docs/tutorials/notebooks/Semigroups,_Monoids_and_Groups.ipynb

This is a pull request for the Semigroups, Monoids and Groups notebook tutorial.

Semigroups. Monoids and Groups notebook tutorial.

---

docs/tutorials/notebooks/Futoshiki.ipynb

Pull request for Futoshiki notebook tutorial.

Futoshiki notebook tutorial

---

docs/tutorials/notebooks/Handcrafting_Instance_Generators_in_Essence.ipynb

This is the pull request for Handcrafting Instance Generators notebook tutorial.

Handcrafting Instance Generators notebook tutorial.

---

docs/tutorials/notebooks/SimplePermutations.ipynb

This is a pull request for the Simple Permutations notebook tutorial.

Simple Permutations notebook tutorial.

---

src/Conjure/UI/MainHelper.hs
tests/custom/issues/578/d/p.param
tests/custom/issues/578/e.essence
tests/custom/issues/578/q.param
tests/custom/issues/578/run.sh
tests/custom/issues/578/stdout.expected

Fix copy solution in subdir

---

docs/bits/operator/L_Div.md
docs/notebooks/division_and_mod_demonstration.ipynb
docs/notebooks/division_n_fractions.ipynb
docs/notebooks/division_n_fractions.ipynb:Zone.Identifier

Just added the n-fractions notebook and added link to the div.md page. Mostly trying this out.

added n-fractions notebook

---

docs/bits/attribute/L_bijective.md
docs/bits/attribute/L_injective.md
docs/bits/attribute/L_maxSize.md
docs/bits/attribute/L_minSize.md
docs/bits/attribute/L_size.md
docs/bits/attribute/L_surjective.md
docs/bits/attribute/L_total.md
docs/bits/type/function.md
docs/notebooks/L_bool.ipynb
docs/notebooks/division_and_mod_demonstration.ipynb
docs/notebooks/division_n_fractions.ipynb
docs/notebooks/functionDemonstration.ipynb
docs/notebooks/magicHexagon.ipynb

links were incorrect (again) so I have fixed them.

N j martin fixing links

---

.github/workflows/release.yml

We still need to compile macos-arm executables manually, but the rest are auto-generated.

Set up github actions to make a release automatically

---

src/Conjure/UI/IO.hs
tests/custom/astjson-roundtrip/run.sh
tests/custom/astjson-roundtrip/sample.essence
tests/custom/astjson-roundtrip/stdout.expected

restore the ability to parse from astjson output. not sure when we lost this ability! added regression test case so it doesn't happen again.

astjson parsing

---

src/Conjure/Process/ValidateConstantForDomain.hs
tests/custom/issues/446/inst.param
tests/custom/issues/446/inst2.param
tests/custom/issues/446/model.essence
tests/custom/issues/446/run.sh
tests/custom/issues/446/stdout.expected

fixing this directly now that I finally decided to abandon #540...

adding a explicit check for sequence size and surjectivity - fixes #446

---

docs/bits/function/defined.md
docs/bits/function/image.md
docs/bits/function/imageSet.md
docs/bits/function/inverse.md
docs/bits/function/preImage.md
docs/bits/function/range.md
docs/bits/function/restrict.md
docs/notebooks/Function_operators.ipynb

Function operators

---

docs/bits/operator/L_subsequence.md
docs/bits/operator/L_substring.md
docs/notebooks/Sequence_operators.ipynb

@N-J-Martin I have done this part, plz have a look! Thanks!

Sequence operators

---

Dockerfile
etc/build/install-minizinc.sh

Hi, I have added a script to install minizinc and updated the Dockerfile to install minizinc.

Added minizinc

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/test-coverage.yml
.github/workflows/test.yml
Makefile
etc/hs-deps/stack-9.10.yaml
etc/hs-deps/stack-9.8.yaml
src/Conjure/Language/Validator.hs

[Update stackage versions and add 9.10 support](https://github.com/conjure-cp/conjure/commit/2ed7aad61b034a6cb237a7c10df7e528da3d378a)
[Add 9.10 to CI and make it the default](https://github.com/conjure-cp/conjure/commit/388a62ef50c447838bd171f0e1c87ff121291f4d)

Support GHC 9.10
